Repository arfc/arfc.github.io, pull requests merged in 2019-09, with the labels that each got.

#145 Additional content for the input example.
  software/moltres/wiki/figures/input_example_mesh.png
  software/moltres/wiki/input_example.md
Labels: Comp:Output, Difficulty:1-Beginner, Status:5-In Review, Type:Docs

#151 Updates for issue #148
  _data/presentations.yml
  img/pres/2019-07-04-kamuda-cvt.jpeg
  img/pres/2019-07-10-kamuda-scipy.png
  pres/2019-07-04-kamuda-cvt.pdf
Labels: Comp:Output, Difficulty:1-Beginner, Priority:2-Normal, Status:5-In Review, Type:Bug

#153 Diversion Detection in Cyclus Name Mismatch
  pres/2019-06-28-pyre-twofcs.pdf
Labels: Comp:Core, Difficulty:1-Beginner, Priority:1-Critical
