Repository arfc/arfc.github.io, pull requests merged in 2020-07, with the labels that each got.

#186 Adding a page to the Guides about PR Reviews
  manual/guides/guides.md
  manual/guides/pull_requests.md
Labels: Comp:Core, Difficulty:1-Beginner, Priority:4-Low, Status:1-New, Type:Docs

#188 Amber Hunter information added for website
  _data/people.yml
  img/people/huntera.png
Labels: Comp:Core, Difficulty:1-Beginner, Priority:2-Normal, Status:5-In Review, Type:Feature

#189 Adds a link for reviewers in the PR Template to the PR Review Checklist
  .github/pull_request_template.md
Labels: Comp:Build, Difficulty:1-Beginner, Priority:3-Desired, Status:5-In Review, Type:Docs

#194 Adding information on getting a Serpent License
  manual/guides/getting_serpent_license.md
  manual/guides/guides.md
Labels: Comp:Core, Difficulty:1-Beginner, Priority:3-Desired, Status:1-New, Type:Feature
