Repository arfc/arfc.github.io, pull requests merged in 2020-08, with the labels that each got.

#196 Add a links to the writing page for conference posters
  manual/guides/writing/conf-poster.md
Labels: Comp:Output, Difficulty:1-Beginner, Priority:4-Low, Status:5-In Review, Type:Docs

#195 Updating the Writing Checklist
  manual/guides/writing/checklist.md
Labels: Comp:Core, Difficulty:1-Beginner, Priority:2-Normal, Status:5-In Review, Type:Docs

#198 Adding Olek to website
  _data/people.yml
  img/people/yardaso.jpeg
Labels: Comp:Core, Difficulty:1-Beginner, Priority:2-Normal, Status:5-In Review, Type:Docs, Type:Feature

#199 Added myself to the website
  _data/people.yml
  img/people/BachmannA.png
Labels: Comp:Core, Difficulty:1-Beginner, Priority:2-Normal, Status:4-In Progress, Type:Docs, Type:Feature
