Repository arfc/arfc.github.io, pull requests merged in 2020-06, with the labels that each got.

#181 Adding a page to the Guides about PyNE
  manual/guides/guides.md
  manual/guides/pyne.md
Labels: Comp:Core, Difficulty:1-Beginner, Priority:2-Normal, Status:5-In Review, Type:Docs

#182 Adding a page to the Guides about Courses
  manual/guides/courses.md
  manual/guides/guides.md
Labels: Comp:Core, Difficulty:1-Beginner, Priority:2-Normal, Status:5-In Review, Type:Docs

#183 Adds Fairhurst ANS Annual Meeting presentation
  _data/presentations.yml
  img/pres/2020-06-10-fairhurst-ans.png
  pres/2020-06-10-fairhurst-ans.pdf
Labels: Comp:Core, Priority:3-Desired, Status:1-New, Type:Docs

#179 adds dotson ans pres 2020
  _data/presentations.yml
  img/pres/2020-06-10-dotson-ans.png
  pres/2020-06-10-dotson-ans2020.pdf
Labels: Comp:Core, Priority:2-Normal, Status:5-In Review, Type:Docs
