Repository arfc/arfc.github.io, pull requests merged in 2021-07, with the labels that each got.

#229 Added Summer 2021 Presentations
  _bibliography/references.bib
  _data/presentations.yml
  img/pres/2021-04-08-bachmann-ans.png
  img/pres/2021-06-16-bachmann-annual.png
  img/pres/2021-06-28-bachmann-twofcs.png
  pres/2021-bachmann-annual.pdf
  pres/2021-bachmann-twofcs.pdf
Labels: Comp:Core, Priority:3-Desired, Status:5-In Review, Type:Docs

#230 Andrei removed from People and added to Alumni
  _data/alumni.yml
  _data/people.yml
Labels: Comp:Input, Difficulty:1-Beginner, Priority:1-Critical, Status:4-In Progress, Type:Docs

#228 Writing Checklist Example Typo
  manual/guides/writing/checklist.md
Labels: Comp:Output, Difficulty:1-Beginner, Priority:4-Low, Status:5-In Review, Type:Docs
