Repository arfc/arfc.github.io, pull requests merged in 2021-11, with the labels that each got.

#235 Update Alumni and Current Pages of the site
  _data/alumni.yml
  _data/people.yml
Labels: Comp:Build, Difficulty:1-Beginner, Priority:3-Desired, Status:5-In Review, Type:Docs

#242 Add munkm to group webpage
  _data/people.yml
  img/people/munkm.jpg
Labels: Comp:Build, Difficulty:1-Beginner, Priority:3-Desired

#241 Change the apostrophe on Kip's description to quotes
  _data/alumni.yml
Labels: Comp:Build, Difficulty:1-Beginner, Priority:4-Low, Status:5-In Review, Type:Bug

#243 Add @yardasol GitHub link
  _data/people.yml
Labels: Priority:2-Normal, Status:5-In Review, Type:Feature
