Repository arfc/arfc.github.io, pull requests merged in 2022-04, with the labels that each got.

#236 added Gabriele Paciocco personal details to data
  _data/people.yml
  img/people/pacioccog.png
Labels: Comp:Build, Difficulty:1-Beginner, Priority:4-Low, Status:5-In Review, Type:Docs

#254 Add presentation from NCSU Building Future Faculty
  _bibliography/references.bib
  _data/presentations.yml
  img/pres/2022-03-31-bachmann-bff.png
  pres/2022-03-31-bachmann-bff.pdf
Labels: Difficulty:1-Beginner, Priority:3-Desired, Status:5-In Review, Type:Docs

#256 Fix typo in Gabriele Paciocco's `people.yml` entry
  _data/people.yml
Labels: Comp:Build, Priority:1-Critical, Status:5-In Review, Type:Bug
