Repository arfc/arfc.github.io, pull requests merged in 2024-07, with the labels that each got.

#321 Make link from the PR template absolute to website checklist
  .github/pull_request_template.md
Labels: Comp:Output, Difficulty:1-Beginner, Priority:2-Normal, Status:5-In Review, Type:Bug

#319 Additional point under Enhancing Clarity
  manual/guides/writing/checklist.md
Labels: Comp:Output, Difficulty:1-Beginner, Priority:3-Desired, Status:5-In Review, Type:Docs

#317 Add openmcyclus to software list
  _data/navbar.yml
  _data/projects.yml
  img/research/openmcyclus_generic.png
Labels: Difficulty:1-Beginner, Priority:3-Desired, Status:1-New, Type:Docs
