Repository arfc/arfc.github.io, pull requests merged in 2024-05, with the labels that each got.

#300 Issue273 : Fixing missing university logo in header
  _includes/header.html
  img/block_i.png
Labels: Comp:Core, Difficulty:1-Beginner, Priority:3-Desired, Status:1-New, Type:Bug

#305 updates link from old one which is dead to new one on i-share
  manual/guides/guides.md
Labels: Comp:Output, Difficulty:1-Beginner, Priority:3-Desired, Status:5-In Review, Type:Bug

#307 Add Owen to website
  _data/people.yml
  img/people/strongo.jpg
Labels: Comp:Output, Difficulty:1-Beginner, Priority:3-Desired, Status:5-In Review, Type:Feature
