Repository arfc/arfc.github.io, pull requests merged in 2025-03, with the labels that each got.

#397 Add nonumber to checklist equation
  manual/guides/writing/checklist.md
Labels: Comp:Output, Difficulty:1-Beginner, Priority:4-Low, Status:5-In Review, Type:Bug

#393 Add openmc guide
  manual/guides/guides.md
  manual/guides/openmc.md
Labels: Difficulty:1-Beginner, Priority:2-Normal

#398 Create plotting file and update guides page
  manual/guides/guides.md
  manual/guides/plots.md
Labels: Comp:Output, Difficulty:1-Beginner, Priority:4-Low, Status:5-In Review, Type:Docs
