Repository arfc/arfc.github.io, pull requests merged in 2025-02, with the labels that each got.

#366 Update 'Acquiring a Serpent License' Guide
  manual/guides/getting_serpent_license.md
Labels: Difficulty:1-Beginner, Priority:2-Normal, Type:Bug

#363 adds instructions so folks can build the website
  README.md
Labels: Comp:Build, Difficulty:1-Beginner, Priority:2-Normal, Status:5-In Review, Type:Docs

#364 Moves Riley to Alumni Page
  _data/alumni.yml
  _data/people.yml
Labels: Comp:Output, Difficulty:1-Beginner, Priority:2-Normal, Status:5-In Review, Type:Docs

#392 change cyclus install guide link to the fuelcycle install page
  manual/guides/cyclus.md
  manual/guides/guides.md
Labels: Comp:Output, Difficulty:1-Beginner, Status:5-In Review, Type:Docs

#391 Add link to CRediT taxonomy for authorship and acknowledgements
  manual/guides/writing.md
Labels: Comp:Output, Difficulty:1-Beginner, Priority:3-Desired, Status:5-In Review, Type:Docs

#394 fix hyperlink in travel guide
  manual/guides/travel.md
Labels: Difficulty:1-Beginner, Priority:2-Normal, Status:5-In Review

#396 Added Samar Abdelkawy to the Website
  _data/people.yml
  img/people/abdelkawys.png
Labels: Difficulty:1-Beginner, Priority:2-Normal
